server {
    listen       8080 default_server;
    root         /var/www/html/;
    index        index.html;
    gzip_static  on;
    gzip_proxied expired no-cache no-store private auth;

    location / {
      gzip_static  on;
      gzip_proxied expired no-cache no-store private auth;
      try_files $uri $uri/ /index.html;
    }
}
